# **데이터 전처리**

In [1]:
import pandas as pd

In [2]:
df_starbucks = pd.read_csv('/content/drive/MyDrive/AI활용 멀티모달 MCP PJ 시즌1/2. 데이터 분석/data/starbucks_seoul.csv')
df_starbucks

         store                                   addr        lat         lng
0    역삼아레나빌딩                  서울특별시 강남구 언주로 425 (역삼동)  37.501087  127.043069
1     논현역사거리                 서울특별시 강남구 강남대로 538 (논현동)  37.510178  127.022223
2    신사역성일빌딩                 서울특별시 강남구 강남대로 584 (논현동)  37.513931  127.020606
3     국기원사거리                 서울특별시 강남구 테헤란로 125 (역삼동)  37.499517  127.031495
4     대치재경빌딩               서울특별시 강남구 남부순환로 2947 (대치동)  37.494668  127.062583
..         ...                                    ...        ...         ...
687      면목역                  서울특별시 중랑구 면목로 403 (면목동)  37.587880  127.087609
688       묵동    서울특별시 중랑구 동일로 952 (묵동, 로프트원 태릉입구역) 1층  37.615368  127.076633
689      망우동                  서울특별시 중랑구 망우로 407 (망우동)  37.599508  127.097539
690      양원역                서울특별시 중랑구 양원역로10길 3 (망우동)  37.606654  127.106360
691      중화역                     서울특별시 중랑구 봉화산로 35 1층  37.601709  127.078411

[692 rows x 4 columns]

In [3]:
df_starbucks = df_starbucks.set_axis(['지점명','지점주소','지점위도','지점경도'], axis=1).reset_index(drop=True)
df_starbucks

           지점명                                   지점주소       지점위도        지점경도
0    역삼아레나빌딩                  서울특별시 강남구 언주로 425 (역삼동)  37.501087  127.043069
1     논현역사거리                 서울특별시 강남구 강남대로 538 (논현동)  37.510178  127.022223
2    신사역성일빌딩                 서울특별시 강남구 강남대로 584 (논현동)  37.513931  127.020606
3     국기원사거리                 서울특별시 강남구 테헤란로 125 (역삼동)  37.499517  127.031495
4     대치재경빌딩               서울특별시 강남구 남부순환로 2947 (대치동)  37.494668  127.062583
..         ...                                    ...        ...         ...
687      면목역                  서울특별시 중랑구 면목로 403 (면목동)  37.587880  127.087609
688       묵동    서울특별시 중랑구 동일로 952 (묵동, 로프트원 태릉입구역) 1층  37.615368  127.076633
689      망우동                  서울특별시 중랑구 망우로 407 (망우동)  37.599508  127.097539
690      양원역                서울특별시 중랑구 양원역로10길 3 (망우동)  37.606654  127.106360
691      중화역                     서울특별시 중랑구 봉화산로 35 1층  37.601709  127.078411

[692 rows x 4 columns]

In [4]:
df = pd.read_csv("/content/drive/MyDrive/AI활용 멀티모달 MCP PJ 시즌1/2. 데이터 분석/data/소상공인시장진흥공단_상가(상권)정보_서울_202510.csv", low_memory=False)
df

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
0,MA010120220802495368,영어독서클럽영어교습소,NaN,P1,교육,P105,일반 교육,P10501,입시·교과학원,P85631,...,1150010200106960000025433,세신그린코아빌딩,서울특별시 강서구 공항대로41길 51,157930,7586,NaN,NaN,NaN,126.845780,37.560238
1,MA010120220806509545,하루달곰,NaN,I2,음식,I210,기타 간이,I21001,빵/도넛,I56191,...,1135010500113100000008002,비콘드림힐,서울특별시 노원구 상계로1길 82-14,139816,1693,301,NaN,NaN,127.062003,37.659314
2,MA010120220804193917,양산박,NaN,I2,음식,I201,한식,I20101,백반/한정식,I56111,...,1165010200102670000002838,명칭없음,서울특별시 서초구 언남11길 34-1,137895,6776,NaN,1,NaN,127.043051,37.475637
3,MA010120220805914597,으뜸공인중개사사무소,NaN,L1,부동산,L102,부동산 서비스,L10203,부동산 중개/대리업,L68221,...,1144010900100100132005798,NaN,서울특별시 마포구 숭문길 182,121870,4122,NaN,1,NaN,126.946651,37.554524
4,MA010120220814395227,세선티알엠,NaN,N1,시설관리·임대,N103,조경·유지,N10301,조경 유지·관리 서비스업,N74300,...,1162010200103050030004243,NaN,서울특별시 관악구 호암로 538,151929,8821,NaN,NaN,NaN,126.931669,37.465579
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
536256,MA0101202306A0044326,신인류,NaN,I2,음식,I211,주점,I21104,요리 주점,I56219,...,1111013800100840003013815,NaN,서울특별시 종로구 종로 72-1,110122,3189,NaN,4,NaN,126.985466,37.569952
536257,MA0101202306A0026957,휴,NaN,I2,음식,I201,한식,I20101,백반/한정식,I56111,...,1168010100107350017000001,역삼푸르지오시티,서울특별시 강남구 논현로85길 52,135923,6235,NaN,2,NaN,127.033813,37.498192
536258,MA0101202306A0041780,참기름짜는육회집,NaN,I2,음식,I201,한식,I20108,소고기 구이/찜,I56113,...,1171011100101460008016117,NaN,서울특별시 송파구 백제고분로48길 19,138832,5632,NaN,1,NaN,127.115414,37.511187
536259,MA0101202306A0033595,신사공인중개사사무소,NaN,L1,부동산,L102,부동산 서비스,L10203,부동산 중개/대리업,L68221,...,1168010700105660018010886,NaN,서울특별시 강남구 논현로157길 18,135891,6032,NaN,1,NaN,127.026663,37.522512
536260,MA0101202306A0015005,거마농장,NaN,I2,음식,I201,한식,I20107,돼지고기 구이/찜,I56113,...,1171011300100360013023025,동인빌타운,서울특별시 송파구 거마로2길 24,138814,5768,NaN,NaN,NaN,127.147309,37.493249

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 536261 entries, 0 to 536260
Data columns (total 39 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   상가업소번호     536261 non-null  object
 1   상호명        536261 non-null  object
 2   지점명        47467 non-null   object
 3   상권업종대분류코드  536261 non-null  object
 4   상권업종대분류명   536261 non-null  object
 5   상권업종중분류코드  536261 non-null  object
 6   상권업종중분류명   536261 non-null  object
 7   상권업종소분류코드  536261 non-null  object
 8   상권업종소분류명   536261 non-null  object
 9   표준산업분류코드   536060 non-null  object
 10  표준산업분류명    536060 non-null  object
 11  시도코드       536261 non-null  int64
 12  시도명        536261 non-null  object
 13  시군구코드      536261 non-null  int64
 14  시군구명       536261 non-null  object
 15  행정동코드      536261 non-null  int64
 16  행정동명       536261 non-null  object
 17  법정동코드      536261 non-null  int64
 18  법정동명       536261 non-null  object
 19  지번코드       536261 non-null  int64
 20  대지구분코드     536261 non-null  int64
 21  대지구분명      536261 non-null  object
 22  지번본번지      536236 non-null  float64
 23  지번부번지      441463 non-null  float64
 24  지번주소       536261 non-null  object
 25  도로명코드      536261 non-null  int64
 26  도로명        536261 non-null  object
 27  건물본번지      536259 non-null  float64
 28  건물부번지      69643 non-null   float64
 29  건물관리번호     533879 non-null  object
 30  건물명        261481 non-null  object
 31  도로명주소      536261 non-null  object
 32  구우편번호      536261 non-null  int64
 33  신우편번호      536261 non-null  int64
 34  동정보        53288 non-null   object
 35  층정보        356978 non-null  object
 36  호정보        0 non-null       float64
 37  경도         536261 non-null  float64
 38  위도         536261 non-null  float64
dtypes: float64(7), int64(9), object(23)
memory usage: 159.6+ MB

In [6]:
shop = ['이디야', '이디아커피', '올리브영', '컴포즈커피', '빽다방', '백다방', '메가커피', '메가엠지씨', '메가MGC']

In [7]:
# contains : 특정 문자열 포함 여부에 따라 True, False를 반환
# case : False일 경우 대소문자를 구분하지 않음
# na : 결측치가 있는 경우 False로 간주
df[df['상호명'].str.contains('메가엠지씨' ,case=False, na=False)]

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
3223,MA0101202301A0006057,메가엠지씨커피노원역점,NaN,I2,음식,I212,비알코올,I21201,카페,I56221,...,1135010500107090002000001,메가빌딩,서울특별시 노원구 노해로 459,139942,1689,NaN,1,NaN,127.058996,37.654252
3321,MA0101202302A0108581,메가엠지씨커피여의도KBS점,NaN,I2,음식,I212,비알코올,I21201,카페,I56221,...,1156011000100170000031660,여의도더샵아일랜드파크,서울특별시 영등포구 의사당대로 38,150916,7236,102,1,NaN,126.918208,37.525550
3580,MA0101202302A0054476,메가엠지씨커피올림픽공원역점,NaN,I2,음식,I212,비알코올,I21201,카페,I56221,...,1171011100100890011015454,올림픽프라자,서울특별시 송파구 양재대로 1222,138151,5648,NaN,1,NaN,127.131064,37.515730
4036,MA0101202302A0078446,메가엠지씨커피방배카페,거리점,I2,음식,I212,비알코올,I21201,카페,I56221,...,1165010100107600002015591,NaN,서울특별시 서초구 방배중앙로 188,137828,6553,2,1,NaN,126.985887,37.495682
4389,MA0101202302A0024271,메가엠지씨커피강남,자곡점,I2,음식,I212,비알코올,I21201,카페,I56221,...,1168011200106580000000001,강남힐스테이트에코,서울특별시 강남구 자곡로 202,135190,6373,NaN,1,NaN,127.105002,37.474697
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
534235,MA0101202306A0046682,메가엠지씨커피강남못골도서관점,NaN,I2,음식,I212,비알코올,I21201,카페,I56221,...,1168011200106360000000001,서강프라자,서울특별시 강남구 자곡로 114,135190,6373,NaN,1,NaN,127.096023,37.472056
535301,MA0101202306A0037162,메가엠지씨커피충무로역점,NaN,I2,음식,I212,비알코올,I21201,카페,I56221,...,1114013700100510011017687,하니맨션,서울특별시 중구 퇴계로 195,100867,4557,NaN,1,NaN,126.993583,37.561357
535886,MA0101202306A0065301,메가엠지씨커피삼성,중앙역점,I2,음식,I212,비알코올,I21201,카페,I56221,...,1168010500101190000026276,NaN,서울특별시 강남구 봉은사로 478,135509,6154,NaN,1,NaN,127.052777,37.512637
536141,MA0101202306A0013543,메가엠지씨커피가산그레이트밸리점,NaN,I2,음식,I212,비알코올,I21201,카페,I56221,...,1154510100100600005000001,갑을그레이트밸리,서울특별시 금천구 디지털로9길 32,153709,8512,NaN,1,NaN,126.887280,37.479636
536186,MA0101202305A0037173,메가엠지씨커피고덕역점,NaN,I2,음식,I212,비알코올,I21201,카페,I56221,...,1174010100100470010018714,성은빌딩,서울특별시 강동구 동남로75길 13-15,134825,5269,NaN,1,NaN,127.155496,37.553623

In [8]:
df[df['상호명'].str.contains('메가커피' ,case=False, na=False)]

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
1810,MA010120220808836788,메가커피고투몰점,NaN,I2,음식,I212,비알코올,I21201,카페,I56191,...,1165010700100190003000001,지하도상가,서울특별시 서초구 신반포로 176,137726,6546,G,NaN,NaN,127.002409,37.503936
5975,MA010120220811952416,메가커피서울대,입구점,I2,음식,I212,비알코올,I21201,카페,I56221,...,1162010100116730021032549,NaN,서울특별시 관악구 남부순환로 1861,151726,8739,NaN,1,NaN,126.956868,37.479998
7389,MA010120220813125772,메가커피수락산역점,NaN,I2,음식,I212,비알코올,I21201,카페,I56221,...,1135010500112670000009826,토마토파르코,서울특별시 노원구 동일로 1700,139876,1624,NaN,NaN,NaN,127.055820,37.680184
41536,MA010120220808992892,메가커피북한산정릉점,NaN,I2,음식,I212,비알코올,I21201,카페,I56221,...,1129013300107800000027020,산장아파트,서울특별시 성북구 보국문로 167,136768,2704,NaN,NaN,NaN,127.001892,37.616660
43300,MA010120220800505619,메가커피우,장산점,I2,음식,I212,비알코올,I21201,카페,I56221,...,1150010600107230008009245,좌,서울특별시 강서구 강서로45길 6,157835,7639,NaN,1,NaN,126.835813,37.548097
53150,MA010120220814193356,메가커피동소문점,NaN,I2,음식,I212,비알코올,I21201,카페,I56221,...,1129011900100420000043999,NaN,서울특별시 성북구 아리랑로 14,136054,2829,NaN,NaN,NaN,127.016396,37.593972
55603,MA010120220805197325,메가커피노원,로데오점,I2,음식,I212,비알코올,I21201,카페,I56221,...,1135010500105930002007922,동원빌딩,서울특별시 노원구 상계로3길 16,139821,1693,NaN,1,NaN,127.062489,37.656981
96952,MA010120220802678209,메가커피문정,아이파크점,I2,음식,I212,비알코올,I21201,카페,I56221,...,1171010800100000000000002,문정아이파크,서울특별시 송파구 법원로4길 6,138888,5855,1,NaN,NaN,127.122108,37.482312
104923,MA010120220812196839,메가커피문정로데오,NaN,I2,음식,I212,비알코올,I21201,카페,I56221,...,1171010700101200004007204,가락우성2차,서울특별시 송파구 중대로12길 35,138806,5832,102,1,NaN,127.125719,37.491589
107486,MA010120220803145703,메가커피현대,시장점,I2,음식,I212,비알코올,I21201,카페,I56221,...,1162010100104640002033874,NaN,서울특별시 관악구 은천로 113,151825,8729,NaN,1,NaN,126.947931,37.486950
111754,MA010120220811858271,메가커피상계역점,NaN,I2,음식,I212,비알코올,I21201,카페,I56221,...,1135010600101540022010063,NaN,서울특별시 노원구 덕릉로83길 18,139856,1662,NaN,1,NaN,127.074414,37.660136
120101,MA010120220807070602,메가커피,NaN,I2,음식,I212,비알코올,I21201,카페,I56221,...,1153010200101970028026783,NaN,서울특별시 구로구 디지털로31길 41,152719,8375,NaN,NaN,NaN,126.892756,37.485165
120378,MA010120220808157025,메가커피노량진역점,NaN,I2,음식,I212,비알코올,I21201,카페,I56221,...,1159010100100440018031551,NaN,서울특별시 동작구 노량진로 126,156052,6928,NaN,1,NaN,126.939679,37.513165
131906,MA010120220808463723,메가커피,NaN,I2,음식,I212,비알코올,I21201,카페,I56221,...,1123010100100840005039356,NaN,서울특별시 동대문구 왕산로 3,130810,2581,NaN,1,NaN,127.023660,37.576212
134823,MA010120220810074917,메가커피사가정역점,NaN,I2,음식,I212,비알코올,I21201,카페,I56221,...,1126010100106170001020698,NaN,서울특별시 중랑구 면목로 316,131828,2249,NaN,1,NaN,127.088338,37.580074
154043,MA010120220813957016,메가커피,화곡역점,I2,음식,I212,비알코올,I21201,카페,I56221,...,1150010300110740024012840,NaN,서울특별시 강서구 화곡로 160,157925,7715,NaN,1,NaN,126.839449,37.541165
154132,MA010120220804156243,메가커피신도림역점,NaN,I2,음식,I212,비알코올,I21201,카페,I56221,...,1153010100103370000000004,신도림푸르지오1차,서울특별시 구로구 경인로 661,152748,8208,NaN,NaN,NaN,126.887767,37.509532
173617,MA010120220812511902,메가커피,공덕점,I2,음식,I212,비알코올,I21201,카페,I56221,...,1144010400101810001003288,일부,서울특별시 마포구 새창로 10,121812,4168,NaN,1,NaN,126.951039,37.542120
177280,MA010120220803387874,메가커피신곡,시장점,I2,음식,I212,비알코올,I21201,카페,I56221,...,1147010300105370008011026,NaN,서울특별시 양천구 신월로 175,158840,8030,NaN,1,NaN,126.842540,37.518842
177847,MA010120220814337194,메가커피신창,시장점,I2,음식,I212,비알코올,I21201,카페,I56221,...,1132010700105690085014923,NaN,서울특별시 도봉구 덕릉로 238,132917,1473,NaN,NaN,NaN,127.038658,37.638971
184440,MA010120220804149613,메가커피,장안점,I2,음식,I212,비알코올,I21201,카페,I56221,...,1123010600103660001016482,풍양빌딩,서울특별시 동대문구 장한로 116,130840,2639,NaN,1,NaN,127.071065,37.570733
199505,MA010120220810112788,메가커피양천신정,중앙점,I2,음식,I212,비알코올,I21201,카페,I56221,...,1147010100110250009006373,NaN,서울특별시 양천구 은행정로 17,158861,8086,NaN,1,NaN,126.859684,37.521215
217097,MA010120220808147311,메가커피수색자이,NaN,I2,음식,I212,비알코올,I21201,카페,I56221,...,1138011000102230003000001,수색자이1단지,서울특별시 은평구 수색로 217,122873,3504,NaN,1,NaN,126.898722,37.579622
231762,MA010120220806689213,메가커피이수,태평점,I2,음식,I212,비알코올,I21201,카페,I56221,...,1159010700101320008034007,NaN,서울특별시 동작구 동작대로27길 20,156816,7008,NaN,1,NaN,126.980891,37.487636
231867,MA010120220804461630,메가커피지하도점,강남역,I2,음식,I212,비알코올,I21201,카페,I56221,...,1168010100108210001000001,강남역지하도상가,서울특별시 강남구 테헤란로 101,135933,6134,E,NaN,NaN,127.028057,37.498617
241908,MA010120220812962899,메가커피공덕SK리더스뷰,NaN,I2,음식,I212,비알코올,I21201,카페,I56221,...,1144010200102570003000001,공덕SK리더스뷰1단지,서울특별시 마포구 백범로31길 8,121862,4147,101,1,NaN,126.948807,37.545218
256898,MA010120220800186190,식빵은여기메가커피,NaN,I2,음식,I212,비알코올,I21201,카페,I56221,...,1171010200100030000000001,잠실동잠실역지하도상가,서울특별시 송파구 올림픽로 265,138934,5510,B,NaN,NaN,127.101856,37.513866
264300,MA010120220802241927,메가커피,마곡점,I2,음식,I212,비알코올,I21201,카페,I56221,...,1150010500107570003000001,마곡나루역보타닉비즈타워,서울특별시 강서구 마곡중앙5로1길 20,157805,7788,NaN,1,NaN,126.826712,37.568672
271487,MA010120220813292922,메가커피신월경창,시장점,I2,음식,I212,비알코올,I21201,카페,I56221,...,1147010300104280007010632,NaN,서울특별시 양천구 월정로 53,158832,7930,NaN,1,NaN,126.841521,37.524436
284389,MA010120220804968967,메가커피잠실레이크,팰리스점,I2,음식,I212,비알코올,I21201,카페,I56221,...,1171010600100220017000001,잠실레이크타워,서울특별시 송파구 석촌호수로 140,138837,5600,NaN,1,NaN,127.092505,37.507018
293466,MA010120220812685091,메가커피고대점,NaN,I2,음식,I212,비알코올,I21201,카페,I56221,...,1129012500101010002040214,일부,서울특별시 성북구 고려대로27길 15,136075,2842,NaN,1,NaN,127.029709,37.586996
330455,MA010120220811699241,메가커피신상도점,NaN,I2,음식,I212,비알코올,I21201,카페,I56221,...,1159010200102090018024088,NaN,서울특별시 동작구 양녕로 193,156841,7048,NaN,1,NaN,126.943615,37.498535
336690,MA010120220806394682,메가커피숙대,NaN,I2,음식,I212,비알코올,I21201,카페,I56112,...,1117010400100900015023923,NaN,서울특별시 용산구 한강대로 277-2,140807,4321,NaN,1,NaN,126.972221,37.543064
339390,MA010120220810024637,메가커피,왕십리점,I2,음식,I212,비알코올,I21201,카페,I56221,...,1120010700100010017019315,NaN,서울특별시 성동구 마조로1길 42,133817,4760,NaN,1,NaN,127.039421,37.561116
352030,MA0106202201A0299892,메가커피안국역점,NaN,I2,음식,I212,비알코올,I21201,카페,I56111,...,1111014800101040001018447,NaN,서울특별시 종로구 계동길 33-2,110801,3059,NaN,NaN,NaN,126.986528,37.578917
449410,MA0101202409A0144201,메가커피잠실,지하점,I2,음식,I212,비알코올,I21201,카페,I56221,...,1171010200100030000000001,잠실역2호선,서울특별시 송파구 올림픽로 265,138934,5510,B,NaN,NaN,127.101856,37.513866
455895,MA010120220809673319,메가커피신길,중앙점,I2,음식,I212,비알코올,I21201,카페,I56221,...,1156013200101140001019009,NaN,서울특별시 영등포구 도신로 234,150839,7351,NaN,1,NaN,126.917386,37.511971
485082,MA0101202307A0030912,메가커피금천현대,시장점,I2,음식,I212,비알코올,I21201,카페,I56221,...,1154510300108520031005221,NaN,서울특별시 금천구 독산로 131,153856,8622,NaN,1,NaN,126.904898,37.458947
508277,MA010120220808069247,메가커피신도봉,시장점,I2,음식,I212,비알코올,I21201,카페,I56221,...,1132010600106530018000001,NaN,서울특별시 도봉구 도봉로 727,132846,1350,NaN,1,NaN,127.043219,37.669351
521046,MA0101202302A0064663,메가커피신정이펜하우스점,NaN,I2,음식,I212,비알코올,I21201,카페,I56221,...,1147010100113160000000001,신정이펜하우스3단지,서울특별시 양천구 신정이펜1로 50,158796,8050,상가,1,NaN,126.829351,37.513355

In [9]:
df[df['상호명'].str.contains('메가커피|메가엠지씨|메가MGC' ,case=False, na=False)]

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
1810,MA010120220808836788,메가커피고투몰점,NaN,I2,음식,I212,비알코올,I21201,카페,I56191,...,1165010700100190003000001,지하도상가,서울특별시 서초구 신반포로 176,137726,6546,G,NaN,NaN,127.002409,37.503936
3223,MA0101202301A0006057,메가엠지씨커피노원역점,NaN,I2,음식,I212,비알코올,I21201,카페,I56221,...,1135010500107090002000001,메가빌딩,서울특별시 노원구 노해로 459,139942,1689,NaN,1,NaN,127.058996,37.654252
3321,MA0101202302A0108581,메가엠지씨커피여의도KBS점,NaN,I2,음식,I212,비알코올,I21201,카페,I56221,...,1156011000100170000031660,여의도더샵아일랜드파크,서울특별시 영등포구 의사당대로 38,150916,7236,102,1,NaN,126.918208,37.525550
3580,MA0101202302A0054476,메가엠지씨커피올림픽공원역점,NaN,I2,음식,I212,비알코올,I21201,카페,I56221,...,1171011100100890011015454,올림픽프라자,서울특별시 송파구 양재대로 1222,138151,5648,NaN,1,NaN,127.131064,37.515730
4036,MA0101202302A0078446,메가엠지씨커피방배카페,거리점,I2,음식,I212,비알코올,I21201,카페,I56221,...,1165010100107600002015591,NaN,서울특별시 서초구 방배중앙로 188,137828,6553,2,1,NaN,126.985887,37.495682
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
534235,MA0101202306A0046682,메가엠지씨커피강남못골도서관점,NaN,I2,음식,I212,비알코올,I21201,카페,I56221,...,1168011200106360000000001,서강프라자,서울특별시 강남구 자곡로 114,135190,6373,NaN,1,NaN,127.096023,37.472056
535301,MA0101202306A0037162,메가엠지씨커피충무로역점,NaN,I2,음식,I212,비알코올,I21201,카페,I56221,...,1114013700100510011017687,하니맨션,서울특별시 중구 퇴계로 195,100867,4557,NaN,1,NaN,126.993583,37.561357
535886,MA0101202306A0065301,메가엠지씨커피삼성,중앙역점,I2,음식,I212,비알코올,I21201,카페,I56221,...,1168010500101190000026276,NaN,서울특별시 강남구 봉은사로 478,135509,6154,NaN,1,NaN,127.052777,37.512637
536141,MA0101202306A0013543,메가엠지씨커피가산그레이트밸리점,NaN,I2,음식,I212,비알코올,I21201,카페,I56221,...,1154510100100600005000001,갑을그레이트밸리,서울특별시 금천구 디지털로9길 32,153709,8512,NaN,1,NaN,126.887280,37.479636
536186,MA0101202305A0037173,메가엠지씨커피고덕역점,NaN,I2,음식,I212,비알코올,I21201,카페,I56221,...,1174010100100470010018714,성은빌딩,서울특별시 강동구 동남로75길 13-15,134825,5269,NaN,1,NaN,127.155496,37.553623

In [10]:
df_shop = df.copy()

In [11]:
# ['이디야', '이디아커피', '올리브영', '컴포즈커피', '빽다방', '백다방', '메가커피', '메가엠지씨', '메가MGC']
df_shop['상호명'] = df_shop['상호명'].str.extract('({})'.format('|'.join(shop)))
# '이디야|이디아커피|올리브영|컴포즈커피|빽다방|백다방|메가커피|메가엠지씨|메가MGC'
# extract : 특정 문자열을 퐇마하고 있으면 해당 문자열을 반환, 포함하고 있찌 않으면 NaN을 반환
df_shop['상호명']

0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
         ...
536256    NaN
536257    NaN
536258    NaN
536259    NaN
536260    NaN
Name: 상호명, Length: 536261, dtype: object

In [12]:
df_shop = df_shop.dropna(subset=['상호명']).iloc[:, [0, 1, 14, 37, 38]].reset_index(drop=True)
df_shop

                    상가업소번호    상호명  시군구명          경도         위도
0     MA010120220801142601    이디야  영등포구  126.888601  37.526796
1     MA010120220808836788   메가커피   서초구  127.002409  37.503936
2     MA010120220812797025  컴포즈커피   종로구  126.987638  37.578016
3     MA010120220814215158  컴포즈커피   도봉구  127.027834  37.660084
4     MA010120220808574817    빽다방   광진구  127.093411  37.535353
...                    ...    ...   ...         ...        ...
2537  MA0101202306A0037570  컴포즈커피   강서구  126.861494  37.545526
2538  MA0101202306A0097799  컴포즈커피   강남구  127.033021  37.497580
2539  MA0101202306A0013543  메가엠지씨   금천구  126.887280  37.479636
2540  MA0101202305A0037173  메가엠지씨   강동구  127.155496  37.553623
2541  MA0101202305A0039797    이디야   노원구  127.080375  37.670827

[2542 rows x 5 columns]

In [13]:
df_shop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2542 entries, 0 to 2541
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   상가업소번호  2542 non-null   object
 1   상호명     2542 non-null   object
 2   시군구명    2542 non-null   object
 3   경도      2542 non-null   float64
 4   위도      2542 non-null   float64
dtypes: float64(2), object(3)
memory usage: 99.4+ KB

In [14]:
df_shop['상호명'] = df_shop['상호명'].str.replace('메가엠지씨','메가커피', regex=False)
df_shop['상호명'] = df_shop['상호명'].str.replace('메가MGC','메가커피', regex=False)
df_shop['상호명'] = df_shop['상호명'].str.replace('이디아커피','이디야', regex=False)
df_shop['상호명'] = df_shop['상호명'].str.replace('백다방','빽다방', regex=False)
df_shop

                    상가업소번호    상호명  시군구명          경도         위도
0     MA010120220801142601    이디야  영등포구  126.888601  37.526796
1     MA010120220808836788   메가커피   서초구  127.002409  37.503936
2     MA010120220812797025  컴포즈커피   종로구  126.987638  37.578016
3     MA010120220814215158  컴포즈커피   도봉구  127.027834  37.660084
4     MA010120220808574817    빽다방   광진구  127.093411  37.535353
...                    ...    ...   ...         ...        ...
2537  MA0101202306A0037570  컴포즈커피   강서구  126.861494  37.545526
2538  MA0101202306A0097799  컴포즈커피   강남구  127.033021  37.497580
2539  MA0101202306A0013543   메가커피   금천구  126.887280  37.479636
2540  MA0101202305A0037173   메가커피   강동구  127.155496  37.553623
2541  MA0101202305A0039797    이디야   노원구  127.080375  37.670827

[2542 rows x 5 columns]

In [15]:
df_shop[df_shop['상호명'].str.contains('메가엠지씨', case = False, na=False)]

Empty DataFrame
Columns: [상가업소번호, 상호명, 시군구명, 경도, 위도]
Index: []

In [16]:
print(df_shop.shape)
print(df_starbucks.shape)

(2542, 5)
(692, 4)

In [17]:
df_cross = df_shop.merge(df_starbucks, how='cross')
df_cross

,상가업소번호,상호명,시군구명,경도,위도,지점명,지점주소,지점위도,지점경도
0,MA010120220801142601,이디야,영등포구,126.888601,37.526796,역삼아레나빌딩,서울특별시 강남구 언주로 425 (역삼동),37.501087,127.043069
1,MA010120220801142601,이디야,영등포구,126.888601,37.526796,논현역사거리,서울특별시 강남구 강남대로 538 (논현동),37.510178,127.022223
2,MA010120220801142601,이디야,영등포구,126.888601,37.526796,신사역성일빌딩,서울특별시 강남구 강남대로 584 (논현동),37.513931,127.020606
3,MA010120220801142601,이디야,영등포구,126.888601,37.526796,국기원사거리,서울특별시 강남구 테헤란로 125 (역삼동),37.499517,127.031495
4,MA010120220801142601,이디야,영등포구,126.888601,37.526796,대치재경빌딩,서울특별시 강남구 남부순환로 2947 (대치동),37.494668,127.062583
...,...,...,...,...,...,...,...,...,...
1759059,MA0101202305A0039797,이디야,노원구,127.080375,37.670827,면목역,서울특별시 중랑구 면목로 403 (면목동),37.587880,127.087609
1759060,MA0101202305A0039797,이디야,노원구,127.080375,37.670827,묵동,"서울특별시 중랑구 동일로 952 (묵동, 로프트원 태릉입구역) 1층",37.615368,127.076633
1759061,MA0101202305A0039797,이디야,노원구,127.080375,37.670827,망우동,서울특별시 중랑구 망우로 407 (망우동),37.599508,127.097539
1759062,MA0101202305A0039797,이디야,노원구,127.080375,37.670827,양원역,서울특별시 중랑구 양원역로10길 3 (망우동),37.606654,127.106360
1759063,MA0101202305A0039797,이디야,노원구,127.080375,37.670827,중화역,서울특별시 중랑구 봉화산로 35 1층,37.601709,127.078411

# **2. 하버사인 공식**

Haversine 공식은 구체(구면) 위의 두 점(위도와 경도로 표시됨) 사이의 최단 거리(대원 거리, great-circle distance)를 계산하는 방법입니다. 이 공식은 GPS 좌표(위도와 경도)를 활용하여 지구 표면 위의 거리 계산에 널리 사용됩니다.

<img src ="https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdna%2FSrWGW%2FbtsLpNU6kSG%2FAAAAAAAAAAAAAAAAAAAAACWyPfRAMbpe0b_v6ut8rDPwdQDwSdWFmpo2ovU3Wj0f%2Fimg.png%3Fcredential%3DyqXZFxpELC7KVnFOS48ylbz2pIh7yKj8%26expires%3D1782831599%26allow_ip%3D%26allow_referer%3D%26signature%3DVj82Y%252BoexdHGCmoU6XWxhADA%252F38%253D">

In [18]:
!pip install haversine

Collecting haversine
  Downloading haversine-2.9.0-py2.py3-none-any.whl.metadata (5.8 kB)
Downloading haversine-2.9.0-py2.py3-none-any.whl (7.7 kB)
Installing collected packages: haversine
Successfully installed haversine-2.9.0

In [19]:
from haversine import haversine

In [20]:
df_cross['거리'] = df_cross.apply(lambda x: haversine([x['위도'], x['경도']], [x['지점위도'], x['지점경도']], unit = 'm'), axis = 1)
df_cross

,상가업소번호,상호명,시군구명,경도,위도,지점명,지점주소,지점위도,지점경도,거리
0,MA010120220801142601,이디야,영등포구,126.888601,37.526796,역삼아레나빌딩,서울특별시 강남구 언주로 425 (역삼동),37.501087,127.043069,13920.861778
1,MA010120220801142601,이디야,영등포구,126.888601,37.526796,논현역사거리,서울특별시 강남구 강남대로 538 (논현동),37.510178,127.022223,11928.817729
2,MA010120220801142601,이디야,영등포구,126.888601,37.526796,신사역성일빌딩,서울특별시 강남구 강남대로 584 (논현동),37.513931,127.020606,11729.458260
3,MA010120220801142601,이디야,영등포구,126.888601,37.526796,국기원사거리,서울특별시 강남구 테헤란로 125 (역삼동),37.499517,127.031495,12963.350679
4,MA010120220801142601,이디야,영등포구,126.888601,37.526796,대치재경빌딩,서울특별시 강남구 남부순환로 2947 (대치동),37.494668,127.062583,15756.321588
...,...,...,...,...,...,...,...,...,...,...
1759059,MA0101202305A0039797,이디야,노원구,127.080375,37.670827,면목역,서울특별시 중랑구 면목로 403 (면목동),37.587880,127.087609,9245.236201
1759060,MA0101202305A0039797,이디야,노원구,127.080375,37.670827,묵동,"서울특별시 중랑구 동일로 952 (묵동, 로프트원 태릉입구역) 1층",37.615368,127.076633,6175.544065
1759061,MA0101202305A0039797,이디야,노원구,127.080375,37.670827,망우동,서울특별시 중랑구 망우로 407 (망우동),37.599508,127.097539,8072.993880
1759062,MA0101202305A0039797,이디야,노원구,127.080375,37.670827,양원역,서울특별시 중랑구 양원역로10길 3 (망우동),37.606654,127.106360,7493.583943
1759063,MA0101202305A0039797,이디야,노원구,127.080375,37.670827,중화역,서울특별시 중랑구 봉화산로 35 1층,37.601709,127.078411,7687.492616

In [21]:
# 개별 매장들과 스타벅스와의 최소 거리
df_dis = df_cross.groupby(['상가업소번호', '상호명'])['거리'].min().reset_index()
df_dis

                    상가업소번호    상호명           거리
0     MA010120220800021713  컴포즈커피   692.058445
1     MA010120220800024620    이디야    95.740366
2     MA010120220800026176    이디야  1115.073437
3     MA010120220800033480    이디야    86.856080
4     MA010120220800033806    이디야   336.355071
...                    ...    ...          ...
2537  MA0106202508A0382188    이디야   182.194030
2538  MA0106202508A2292809   올리브영    94.825689
2539  MA0106202508A2292811   올리브영    54.560486
2540  MA0106202508A2293408   올리브영    21.351847
2541  MA0106202508A2293410   올리브영    32.530233

[2542 rows x 3 columns]

In [23]:
df_cross.groupby(['상가업소번호'])['거리'].mean()

상가업소번호
MA010120220800021713     8484.781746
MA010120220800024620     8724.078013
MA010120220800026176    10436.865743
MA010120220800033480     7977.802754
MA010120220800033806     8656.529809
                            ...
MA0106202508A0382188    13022.223182
MA0106202508A2292809     8357.462238
MA0106202508A2292811     8436.677711
MA0106202508A2293408     9179.108862
MA0106202508A2293410     8012.434171
Name: 거리, Length: 2542, dtype: float64

In [24]:
# agg : 다중 집계작업을 간단하게 해주는 함수
df_dis.groupby(['상호명'])['거리'].agg(['mean', 'count'])

             mean  count
상호명
메가커피   356.009564    861
빽다방    291.441092    360
올리브영   193.824447    432
이디야    359.052817    453
컴포즈커피  331.146041    436

In [25]:
# 거리를 입력하면 프렌차이즈 별 스타벅스와의 평균거리와 매장개수를 출력하는 함수
def distance(x):
    dis = df_dis['거리'] <= x
    return df_dis[dis].groupby('상호명')['거리'].agg(['mean', 'count'])

In [26]:
distance(100)

            mean  count
상호명
메가커피   60.736718    158
빽다방    62.070746     93
올리브영   53.099333    200
이디야    66.617860     79
컴포즈커피  61.608697     92

In [27]:
distance(50)

            mean  count
상호명
메가커피   29.548266     49
빽다방    35.921217     32
올리브영   24.090984     82
이디야    35.105113     19
컴포즈커피  31.886087     30

# **3. 차트 시각화**

In [30]:
!pip install pandasecharts

Collecting pandasecharts
  Downloading pandasecharts-0.5-py3-none-any.whl.metadata (2.8 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from pandasecharts) (2.2.2)
Collecting pyecharts>=1.0.0 (from pandasecharts)
  Downloading pyecharts-2.1.0-py3-none-any.whl.metadata (1.5 kB)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from pyecharts>=1.0.0->pandasecharts) (3.1.6)
Requirement already satisfied: prettytable in /usr/local/lib/python3.12/dist-packages (from pyecharts>=1.0.0->pandasecharts) (3.17.0)
Requirement already satisfied: simplejson in /usr/local/lib/python3.12/dist-packages (from pyecharts>=1.0.0->pandasecharts) (4.1.1)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas->pandasecharts) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->pandasecharts) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->pandasecharts) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->pandasecharts) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->pandasecharts) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->pyecharts>=1.0.0->pandasecharts) (3.0.3)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prettytable->pyecharts>=1.0.0->pandasecharts) (0.7.0)
Downloading pandasecharts-0.5-py3-none-any.whl (15 kB)
Downloading pyecharts-2.1.0-py3-none-any.whl (161 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 161.1/161.1 kB 1.6 MB/s eta 0:00:00
Installing collected packages: pyecharts, pandasecharts
Successfully installed pandasecharts-0.5 pyecharts-2.1.0

In [32]:
df_100 = distance(100).reset_index()
df_100

     상호명       mean  count
0   메가커피  60.736718    158
1    빽다방  62.070746     93
2   올리브영  53.099333    200
3    이디야  66.617860     79
4  컴포즈커피  61.608697     92

In [33]:
import IPython
from pandasecharts import echart

df_100.echart.pie(x='상호명', y='count', figsize=(600, 400),
                  radius=['20%', '60%'], label_opts={'position':'outer'},
                  title='커피 프렌차이즈의 입점전략은 과연 스타벅스 옆인가?',
                  legend_opts={'pos_right':'0%', 'orient':'vertical'},
                  subtitle='100m 이내 매장수', init_opts={'bg_color': 'white'}).render()

'/content/render.html'

In [37]:
IPython.display.HTML(filename='render.html')

In [38]:
from pyecharts.charts import Timeline, Grid

tl = Timeline({'width':'600px', 'height':'400px'})

for i in [1000, 100, 50, 30]:
    df_d = distance(i).reset_index()
    pie1 = df_d.echart.pie(x='상호명', y='count', figsize=(600, 400),
                    radius=['20%', '60%'], label_opts={'position':'outer'},
                    title='커피 프렌차이즈의 입점전략은 과연 스타벅스 옆인가?',
                    legend_opts={'pos_right':'0%', 'orient':'vertical'},
                    subtitle='{}m 이내 매장수'.format(i), init_opts={'bg_color': 'white'})
    tl.add(pie1, '{}m'.format(i)).render()
IPython.display.HTML(filename='render.html')